//
//  UIColor+ESYAdditions.swift
//
//  Generated by Zeplin on 7/6/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func esyDuskBlueColor() -> UIColor {
		return UIColor(red: 34.0 / 255.0, green: 83.0 / 255.0, blue: 120.0 / 255.0, alpha: 1.0)
	}

	class func esyOffWhiteColor() -> UIColor {
		return UIColor(red: 242.0 / 255.0, green: 255.0 / 255.0, blue: 227.0 / 255.0, alpha: 1.0)
	}

	class func esyBluegreenColor() -> UIColor {
		return UIColor(red: 23.0 / 255.0, green: 149.0 / 255.0, blue: 163.0 / 255.0, alpha: 1.0)
	}

	class func esyRobinsEggBlueColor() -> UIColor {
		return UIColor(red: 172.0 / 255.0, green: 240.0 / 255.0, blue: 242.0 / 255.0, alpha: 1.0)
	}

	class func esyWhiteColor() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class func esyBlack50Color() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.5)
	}

	class func esyGreyishBrownColor() -> UIColor {
		return UIColor(white: 74.0 / 255.0, alpha: 1.0)
	}
}
